### ISSUE TITLE
Error in Create group

### ISSUE THREAD

**Issue by vickyboston20** [divinorum-webb/tableau-api-lib#44] opened 2021-07-20 14:23 UTC
i Found bug while creating group with active directory.

**To Reproduce:**
`conn.create_group(new_group_name=group_name, active_directory_group_name=ad_group_name, active_directory_domain_name = ad_domain_name, minimum_site_role=site_role, license_mode=mode)`
**Error:**
```
File "/c/Users/tableau-automation/venv/lib/python3.6/site-packages/tableau_api_lib/api_requests/create_group_request.py", line 129, in base_create_active_directory_group_request
    self.required_active_directory_group_param_values[0],
TypeError: update expected at most 1 arguments, got 2
```
i found that error with updating dictionary
**Fix:**
tableau_api_lib/api_requests/create_group_request.py
line 129
```
self._request_body["group"].update(
                name = self.required_active_directory_group_param_values[0],
            )
```

**Comment by divinorum-webb** [comment] 2021-07-21 22:00
@vickyboston20 thanks for calling this out! Can you please `pip install -U tableau-api-lib` and let me know if the issue is resolved for you?

**Comment by divinorum-webb** [comment] 2021-09-27 15:34
@vickyboston20 following up: has running `pip install -U tableau-api-lib` to upgrade the library resolved this issue?

**Comment by divinorum-webb** [comment] 2021-12-28 15:53
Closing as the issue is believed to be resolved.

**Closed by divinorum-webb** 2021-12-28 15:53 UTC
